### PR TITLE
Add Get function - InsightParams

### PR DESCRIPTION
**Pull request by royvandewater**

### CODE REVIEW

**Comment by royvandewater** [comment]
Regarding the identical code that CodeClimate found, I copied the implementation from the `handleCallback` function, I'd be happy to pull that out into a shared method and squash that into the pull request. 

What's the preferred style for a helper function? I'm imagining something like `WemoClient.prototype._parseInsightParams`? I couldn't find a close enough precedent to copy :-)

**Comment by timonreinhard** [comment]
Yeah, introducing a `WemoClient.prototype._parseInsightParams` would be a good thing to go with.

**Comment by royvandewater** [comment]
Ok, this should work better then

**Comment by timonreinhard** [comment]
Good work, thanks for contributing!

**Pull request merged**
